export * from './admin-rcs-controller.service';
import { AdminRcsControllerService } from './admin-rcs-controller.service';
export * from './branching-controller.service';
import { BranchingControllerService } from './branching-controller.service';
export * from './bulk-resource-controller.service';
import { BulkResourceControllerService } from './bulk-resource-controller.service';
export * from './commits-controller.service';
import { CommitsControllerService } from './commits-controller.service';
export * from './computed-metadata-controller.service';
import { ComputedMetadataControllerService } from './computed-metadata-controller.service';
export * from './content-insights-controller.service';
import { ContentInsightsControllerService } from './content-insights-controller.service';
export * from './directory-controller.service';
import { DirectoryControllerService } from './directory-controller.service';
export * from './favicon-configuration.service';
import { FaviconConfigurationService } from './favicon-configuration.service';
export * from './healthcheck-controller.service';
import { HealthcheckControllerService } from './healthcheck-controller.service';
export * from './insight-snapshot-controller.service';
import { InsightSnapshotControllerService } from './insight-snapshot-controller.service';
export * from './insights-view-controller.service';
import { InsightsViewControllerService } from './insights-view-controller.service';
export * from './linking-controller.service';
import { LinkingControllerService } from './linking-controller.service';
export * from './localization-insights-controller.service';
import { LocalizationInsightsControllerService } from './localization-insights-controller.service';
export * from './quality-insights-controller.service';
import { QualityInsightsControllerService } from './quality-insights-controller.service';
export * from './reporting-controller.service';
import { ReportingControllerService } from './reporting-controller.service';
export * from './resource-controller.service';
import { ResourceControllerService } from './resource-controller.service';
export * from './synchronization.service';
import { SynchronizationService } from './synchronization.service';
export * from './version-info-controller.service';
import { VersionInfoControllerService } from './version-info-controller.service';
export const APIS = [AdminRcsControllerService, BranchingControllerService, BulkResourceControllerService, CommitsControllerService, ComputedMetadataControllerService, ContentInsightsControllerService, DirectoryControllerService, FaviconConfigurationService, HealthcheckControllerService, InsightSnapshotControllerService, InsightsViewControllerService, LinkingControllerService, LocalizationInsightsControllerService, QualityInsightsControllerService, ReportingControllerService, ResourceControllerService, SynchronizationService, VersionInfoControllerService];
