/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext 
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { PagedModelQualityIssueDto } from '../model/paged-model-quality-issue-dto';
// @ts-ignore
import { PagedModelQualityScanProgressDto } from '../model/paged-model-quality-scan-progress-dto';
// @ts-ignore
import { QualityIssueCounts } from '../model/quality-issue-counts';
// @ts-ignore
import { QualityIssuesPageDto } from '../model/quality-issues-page-dto';
// @ts-ignore
import { QualityScanProgressDto } from '../model/quality-scan-progress-dto';
// @ts-ignore
import { ScanResourceRequest } from '../model/scan-resource-request';
// @ts-ignore
import { ScanSummaryDto } from '../model/scan-summary-dto';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class ReportingControllerService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * @endpoint get /reporting/scan-summaries/{resourceUuid}
     * @param resourceUuid 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public getHistoricalScanSummaries(resourceUuid: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<Array<ScanSummaryDto>>;
    public getHistoricalScanSummaries(resourceUuid: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<ScanSummaryDto>>>;
    public getHistoricalScanSummaries(resourceUuid: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<ScanSummaryDto>>>;
    public getHistoricalScanSummaries(resourceUuid: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (resourceUuid === null || resourceUuid === undefined) {
            throw new Error('Required parameter resourceUuid was null or undefined when calling getHistoricalScanSummaries.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/reporting/scan-summaries/${this.configuration.encodeParam({name: "resourceUuid", value: resourceUuid, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid"})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<ScanSummaryDto>>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @endpoint get /reporting/quality/{resourceUuid}/latest
     * @param resourceUuid 
     * @param categories 
     * @param severities 
     * @param messageSearch 
     * @param filenameSearch 
     * @param page Zero-based page index (0..N)
     * @param size The size of the page to be returned
     * @param sort Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public getLatestResourceQuality(resourceUuid: string, categories?: Set<'LINKING' | 'VALIDATION_AND_STRUCTURE' | 'ACCESSIBILITY' | 'LOCALIZATION_READINESS' | 'AI_READINESS' | 'UNKNOWN' | 'METADATA_AND_SEO' | 'GOVERNANCE_AND_LIFECYCLE'>, severities?: Set<'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL'>, messageSearch?: string, filenameSearch?: string, page?: number, size?: number, sort?: Array<string>, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<PagedModelQualityIssueDto>;
    public getLatestResourceQuality(resourceUuid: string, categories?: Set<'LINKING' | 'VALIDATION_AND_STRUCTURE' | 'ACCESSIBILITY' | 'LOCALIZATION_READINESS' | 'AI_READINESS' | 'UNKNOWN' | 'METADATA_AND_SEO' | 'GOVERNANCE_AND_LIFECYCLE'>, severities?: Set<'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL'>, messageSearch?: string, filenameSearch?: string, page?: number, size?: number, sort?: Array<string>, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<PagedModelQualityIssueDto>>;
    public getLatestResourceQuality(resourceUuid: string, categories?: Set<'LINKING' | 'VALIDATION_AND_STRUCTURE' | 'ACCESSIBILITY' | 'LOCALIZATION_READINESS' | 'AI_READINESS' | 'UNKNOWN' | 'METADATA_AND_SEO' | 'GOVERNANCE_AND_LIFECYCLE'>, severities?: Set<'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL'>, messageSearch?: string, filenameSearch?: string, page?: number, size?: number, sort?: Array<string>, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<PagedModelQualityIssueDto>>;
    public getLatestResourceQuality(resourceUuid: string, categories?: Set<'LINKING' | 'VALIDATION_AND_STRUCTURE' | 'ACCESSIBILITY' | 'LOCALIZATION_READINESS' | 'AI_READINESS' | 'UNKNOWN' | 'METADATA_AND_SEO' | 'GOVERNANCE_AND_LIFECYCLE'>, severities?: Set<'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL'>, messageSearch?: string, filenameSearch?: string, page?: number, size?: number, sort?: Array<string>, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (resourceUuid === null || resourceUuid === undefined) {
            throw new Error('Required parameter resourceUuid was null or undefined when calling getLatestResourceQuality.');
        }

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'categories',
            <any>categories,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'severities',
            <any>severities,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'messageSearch',
            <any>messageSearch,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'filenameSearch',
            <any>filenameSearch,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'page',
            <any>page,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'size',
            <any>size,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'sort',
            <any>sort,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/reporting/quality/${this.configuration.encodeParam({name: "resourceUuid", value: resourceUuid, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid"})}/latest`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<PagedModelQualityIssueDto>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @endpoint get /reporting/quality/{resourceUuid}/latest/counts
     * @param resourceUuid 
     * @param categories 
     * @param severities 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public getLatestResourceQualityCounts(resourceUuid: string, categories?: Set<'LINKING' | 'VALIDATION_AND_STRUCTURE' | 'ACCESSIBILITY' | 'LOCALIZATION_READINESS' | 'AI_READINESS' | 'UNKNOWN' | 'METADATA_AND_SEO' | 'GOVERNANCE_AND_LIFECYCLE'>, severities?: Set<'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL'>, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<QualityIssueCounts>;
    public getLatestResourceQualityCounts(resourceUuid: string, categories?: Set<'LINKING' | 'VALIDATION_AND_STRUCTURE' | 'ACCESSIBILITY' | 'LOCALIZATION_READINESS' | 'AI_READINESS' | 'UNKNOWN' | 'METADATA_AND_SEO' | 'GOVERNANCE_AND_LIFECYCLE'>, severities?: Set<'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL'>, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<QualityIssueCounts>>;
    public getLatestResourceQualityCounts(resourceUuid: string, categories?: Set<'LINKING' | 'VALIDATION_AND_STRUCTURE' | 'ACCESSIBILITY' | 'LOCALIZATION_READINESS' | 'AI_READINESS' | 'UNKNOWN' | 'METADATA_AND_SEO' | 'GOVERNANCE_AND_LIFECYCLE'>, severities?: Set<'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL'>, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<QualityIssueCounts>>;
    public getLatestResourceQualityCounts(resourceUuid: string, categories?: Set<'LINKING' | 'VALIDATION_AND_STRUCTURE' | 'ACCESSIBILITY' | 'LOCALIZATION_READINESS' | 'AI_READINESS' | 'UNKNOWN' | 'METADATA_AND_SEO' | 'GOVERNANCE_AND_LIFECYCLE'>, severities?: Set<'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL'>, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (resourceUuid === null || resourceUuid === undefined) {
            throw new Error('Required parameter resourceUuid was null or undefined when calling getLatestResourceQualityCounts.');
        }

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'categories',
            <any>categories,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'severities',
            <any>severities,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/reporting/quality/${this.configuration.encodeParam({name: "resourceUuid", value: resourceUuid, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid"})}/latest/counts`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<QualityIssueCounts>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @endpoint get /reporting/quality/{resourceUuid}/latest/with-counts
     * @param resourceUuid 
     * @param categories 
     * @param severities 
     * @param messageSearch 
     * @param filenameSearch 
     * @param page Zero-based page index (0..N)
     * @param size The size of the page to be returned
     * @param sort Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public getLatestResourceQualityWithCounts(resourceUuid: string, categories?: Set<'LINKING' | 'VALIDATION_AND_STRUCTURE' | 'ACCESSIBILITY' | 'LOCALIZATION_READINESS' | 'AI_READINESS' | 'UNKNOWN' | 'METADATA_AND_SEO' | 'GOVERNANCE_AND_LIFECYCLE'>, severities?: Set<'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL'>, messageSearch?: string, filenameSearch?: string, page?: number, size?: number, sort?: Array<string>, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<QualityIssuesPageDto>;
    public getLatestResourceQualityWithCounts(resourceUuid: string, categories?: Set<'LINKING' | 'VALIDATION_AND_STRUCTURE' | 'ACCESSIBILITY' | 'LOCALIZATION_READINESS' | 'AI_READINESS' | 'UNKNOWN' | 'METADATA_AND_SEO' | 'GOVERNANCE_AND_LIFECYCLE'>, severities?: Set<'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL'>, messageSearch?: string, filenameSearch?: string, page?: number, size?: number, sort?: Array<string>, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<QualityIssuesPageDto>>;
    public getLatestResourceQualityWithCounts(resourceUuid: string, categories?: Set<'LINKING' | 'VALIDATION_AND_STRUCTURE' | 'ACCESSIBILITY' | 'LOCALIZATION_READINESS' | 'AI_READINESS' | 'UNKNOWN' | 'METADATA_AND_SEO' | 'GOVERNANCE_AND_LIFECYCLE'>, severities?: Set<'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL'>, messageSearch?: string, filenameSearch?: string, page?: number, size?: number, sort?: Array<string>, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<QualityIssuesPageDto>>;
    public getLatestResourceQualityWithCounts(resourceUuid: string, categories?: Set<'LINKING' | 'VALIDATION_AND_STRUCTURE' | 'ACCESSIBILITY' | 'LOCALIZATION_READINESS' | 'AI_READINESS' | 'UNKNOWN' | 'METADATA_AND_SEO' | 'GOVERNANCE_AND_LIFECYCLE'>, severities?: Set<'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL'>, messageSearch?: string, filenameSearch?: string, page?: number, size?: number, sort?: Array<string>, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (resourceUuid === null || resourceUuid === undefined) {
            throw new Error('Required parameter resourceUuid was null or undefined when calling getLatestResourceQualityWithCounts.');
        }

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'categories',
            <any>categories,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'severities',
            <any>severities,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'messageSearch',
            <any>messageSearch,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'filenameSearch',
            <any>filenameSearch,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'page',
            <any>page,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'size',
            <any>size,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'sort',
            <any>sort,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/reporting/quality/${this.configuration.encodeParam({name: "resourceUuid", value: resourceUuid, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid"})}/latest/with-counts`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<QualityIssuesPageDto>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @endpoint get /reporting/scan-summary/{scanUuid}
     * @param scanUuid 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public getScanSummary(scanUuid: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<ScanSummaryDto>;
    public getScanSummary(scanUuid: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ScanSummaryDto>>;
    public getScanSummary(scanUuid: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ScanSummaryDto>>;
    public getScanSummary(scanUuid: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (scanUuid === null || scanUuid === undefined) {
            throw new Error('Required parameter scanUuid was null or undefined when calling getScanSummary.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/reporting/scan-summary/${this.configuration.encodeParam({name: "scanUuid", value: scanUuid, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid"})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ScanSummaryDto>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @endpoint get /reporting/quality/{resourceUuid}
     * @param resourceUuid 
     * @param page Zero-based page index (0..N)
     * @param size The size of the page to be returned
     * @param sort Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public getScansForResource(resourceUuid: string, page?: number, size?: number, sort?: Array<string>, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<PagedModelQualityScanProgressDto>;
    public getScansForResource(resourceUuid: string, page?: number, size?: number, sort?: Array<string>, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<PagedModelQualityScanProgressDto>>;
    public getScansForResource(resourceUuid: string, page?: number, size?: number, sort?: Array<string>, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<PagedModelQualityScanProgressDto>>;
    public getScansForResource(resourceUuid: string, page?: number, size?: number, sort?: Array<string>, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (resourceUuid === null || resourceUuid === undefined) {
            throw new Error('Required parameter resourceUuid was null or undefined when calling getScansForResource.');
        }

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'page',
            <any>page,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'size',
            <any>size,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'sort',
            <any>sort,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/reporting/quality/${this.configuration.encodeParam({name: "resourceUuid", value: resourceUuid, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid"})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<PagedModelQualityScanProgressDto>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @endpoint post /reporting/scan-resource/{resourceUuid}
     * @param resourceUuid 
     * @param request 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public scanResource(resourceUuid: string, request: ScanResourceRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<QualityScanProgressDto>;
    public scanResource(resourceUuid: string, request: ScanResourceRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<QualityScanProgressDto>>;
    public scanResource(resourceUuid: string, request: ScanResourceRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<QualityScanProgressDto>>;
    public scanResource(resourceUuid: string, request: ScanResourceRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (resourceUuid === null || resourceUuid === undefined) {
            throw new Error('Required parameter resourceUuid was null or undefined when calling scanResource.');
        }
        if (request === null || request === undefined) {
            throw new Error('Required parameter request was null or undefined when calling scanResource.');
        }

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'request',
            <any>request,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/reporting/scan-resource/${this.configuration.encodeParam({name: "resourceUuid", value: resourceUuid, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid"})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<QualityScanProgressDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @endpoint get /reporting/scan-progress/{scanUuid}
     * @param scanUuid 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public scanStatus(scanUuid: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<QualityScanProgressDto>;
    public scanStatus(scanUuid: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<QualityScanProgressDto>>;
    public scanStatus(scanUuid: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<QualityScanProgressDto>>;
    public scanStatus(scanUuid: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (scanUuid === null || scanUuid === undefined) {
            throw new Error('Required parameter scanUuid was null or undefined when calling scanStatus.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/reporting/scan-progress/${this.configuration.encodeParam({name: "scanUuid", value: scanUuid, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid"})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<QualityScanProgressDto>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
