/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Account } from './account';
import { ReleaseDetails } from './release-details';


export interface Branch { 
    id?: number;
    branchName?: string;
    branchUuid?: string;
    ordinal?: number;
    branchNotes?: string;
    branchType?: Branch.BranchTypeEnum;
    createdUtc?: string;
    deletedUtc?: string;
    createdBy?: Account;
    releaseDetails?: ReleaseDetails;
}
export namespace Branch {
    export const BranchTypeEnum = {
        StandardBranch: 'STANDARD_BRANCH',
        Release: 'RELEASE'
    } as const;
    export type BranchTypeEnum = typeof BranchTypeEnum[keyof typeof BranchTypeEnum];
}


