/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResourceResponse } from './resource-response';


export interface BulkResourcesResponse { 
    resourceByUuid?: { [key: string]: ResourceResponse; };
}

