/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResourceVersionResponseDto } from './resource-version-response-dto';


export interface CommitOperationDetailDto { 
    legacyRevisionId?: number;
    operationType?: CommitOperationDetailDto.OperationTypeEnum;
    resourceVersion?: ResourceVersionResponseDto;
}
export namespace CommitOperationDetailDto {
    export const OperationTypeEnum = {
        Create: 'CREATE',
        Update: 'UPDATE',
        Move: 'MOVE',
        Rename: 'RENAME',
        Delete: 'DELETE',
        Branch: 'BRANCH',
        Merge: 'MERGE'
    } as const;
    export type OperationTypeEnum = typeof OperationTypeEnum[keyof typeof OperationTypeEnum];
}


