/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Commit { 
    origin?: Commit.OriginEnum;
    message?: string;
    id?: number;
    commitUuid?: string;
    createdUtc?: string;
    createdAccountUsername?: string;
}
export namespace Commit {
    export const OriginEnum = {
        UnlockWeb: 'UNLOCK_WEB',
        UnlockWebdav: 'UNLOCK_WEBDAV',
        CreateNewWebdav: 'CREATE_NEW_WEBDAV',
        MoveWebdav: 'MOVE_WEBDAV',
        CopyWebdav: 'COPY_WEBDAV',
        Upload: 'UPLOAD',
        ManualCommit: 'MANUAL_COMMIT',
        System: 'SYSTEM',
        RecycleRestore: 'RECYCLE_RESTORE',
        DeleteWebdav: 'DELETE_WEBDAV',
        WebUi: 'WEB_UI',
        Collab: 'COLLAB',
        RestApi: 'REST_API'
    } as const;
    export type OriginEnum = typeof OriginEnum[keyof typeof OriginEnum];
}


