/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommitResponseDto } from './commit-response-dto';
import { CommitOperationDetailDto } from './commit-operation-detail-dto';


export interface CommitWithOpDto { 
    commit?: CommitResponseDto;
    operation?: CommitOperationDetailDto;
}

