/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Context { 
    type?: Context.TypeEnum;
    id?: string;
}
export namespace Context {
    export const TypeEnum = {
        Folder: 'FOLDER',
        Map: 'MAP',
        Branch: 'BRANCH'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


