/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateCommitOperationForResourceDto { 
    resourceUuid?: string;
    legacyRevisionId?: number;
    username?: string;
    operation?: CreateCommitOperationForResourceDto.OperationEnum;
    expectedMd5Hash?: string;
    expectedLastModified?: string;
}
export namespace CreateCommitOperationForResourceDto {
    export const OperationEnum = {
        Create: 'CREATE',
        Update: 'UPDATE',
        Move: 'MOVE',
        Rename: 'RENAME',
        Delete: 'DELETE',
        Branch: 'BRANCH',
        Merge: 'MERGE'
    } as const;
    export type OperationEnum = typeof OperationEnum[keyof typeof OperationEnum];
}


