/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Context } from './context';
import { ScheduleIntervalDto } from './schedule-interval-dto';


export interface CreateScheduleRequest { 
    insightType: CreateScheduleRequest.InsightTypeEnum;
    context?: Context;
    interval: ScheduleIntervalDto;
}
export namespace CreateScheduleRequest {
    export const InsightTypeEnum = {
        Content: 'CONTENT',
        Localization: 'LOCALIZATION',
        Quality: 'QUALITY',
        Reuse: 'REUSE'
    } as const;
    export type InsightTypeEnum = typeof InsightTypeEnum[keyof typeof InsightTypeEnum];
}


