/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateCommitOperationForResourceDto } from './create-commit-operation-for-resource-dto';


export interface CreateCommitForResourcesDto { 
    commitUuid?: string;
    origin?: CreateCommitForResourcesDto.OriginEnum;
    message?: string;
    authorUsername?: string;
    createdUtc?: string;
    operations?: Array<CreateCommitOperationForResourceDto>;
}
export namespace CreateCommitForResourcesDto {
    export const OriginEnum = {
        UnlockWeb: 'UNLOCK_WEB',
        UnlockWebdav: 'UNLOCK_WEBDAV',
        CreateNewWebdav: 'CREATE_NEW_WEBDAV',
        MoveWebdav: 'MOVE_WEBDAV',
        CopyWebdav: 'COPY_WEBDAV',
        Upload: 'UPLOAD',
        ManualCommit: 'MANUAL_COMMIT',
        System: 'SYSTEM',
        RecycleRestore: 'RECYCLE_RESTORE',
        DeleteWebdav: 'DELETE_WEBDAV',
        WebUi: 'WEB_UI',
        Collab: 'COLLAB',
        RestApi: 'REST_API'
    } as const;
    export type OriginEnum = typeof OriginEnum[keyof typeof OriginEnum];
}


