/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Context } from './context';
import { FilterEntry } from './filter-entry';
import { SortField } from './sort-field';
import { CsvColumn } from './csv-column';


export interface CsvExportRequest { 
    context?: Context;
    filters?: Array<FilterEntry>;
    columns?: Array<CsvColumn>;
    sort?: Array<SortField>;
}

