/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DependencyIssue { 
    resourceUuid?: string;
    issues?: DependencyIssue.IssuesEnum;
}
export namespace DependencyIssue {
    export const IssuesEnum = {
        BrokenLink: 'BROKEN_LINK',
        InvalidXml: 'INVALID_XML'
    } as const;
    export type IssuesEnum = typeof IssuesEnum[keyof typeof IssuesEnum];
}


