/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DirectoryResponseDto { 
    directoryUuid?: string;
    parentUuid?: string;
    ezdPath?: string;
    directoryName?: string;
    branchName?: string;
    directoryCreateTime?: string;
    permOwner?: string;
    ownerGroup?: string;
    mode?: string;
    childDirectoriesCount?: number;
    childResourcesCount?: number;
}

