/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DirectorySyncInfoDto } from './directory-sync-info-dto';
import { ResourceSyncInfoDto } from './resource-sync-info-dto';


export interface FileStructureDto { 
    parentDirectoryInfo?: DirectorySyncInfoDto;
    childDirectories?: Array<DirectorySyncInfoDto>;
    childResources?: Array<ResourceSyncInfoDto>;
}

