/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NumberRange } from './number-range';
import { DateInterval } from './date-interval';


export interface FilterEntry { 
    field?: string;
    value?: object;
    list?: Array<object>;
    range?: NumberRange;
    interval?: DateInterval;
    search?: Array<string>;
}

