/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request to preview computed metadata against all DITA resources in a folder
 */
export interface FolderPreviewRequest { 
    /**
     * Value to use when no XPath expression matches
     */
    defaultValue?: string;
    /**
     * XPath expressions to evaluate, tried in ordinal order until one matches
     */
    xpaths?: Array<string>;
    /**
     * UUID of the folder containing resources to preview
     */
    folderUuid: string;
    /**
     * Maximum number of resources to process (1-100)
     */
    limit?: number;
    /**
     * Whether to include resources in subdirectories recursively
     */
    recursive?: boolean;
}

