/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Context } from './context';
import { TrendsConfig } from './trends-config';
import { FilterEntry } from './filter-entry';
import { SummarySpec } from './summary-spec';


export interface InsightsSummaryRequest { 
    summaries?: { [key: string]: SummarySpec; };
    trends?: TrendsConfig;
    callouts?: Array<string>;
    context?: Context;
    filters?: Array<FilterEntry>;
}

