/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SummaryResult } from './summary-result';


export interface InsightsSummary { 
    summaries?: { [key: string]: Array<SummaryResult>; };
    callouts?: { [key: string]: number; };
}

