/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Context } from './context';
import { FilterEntry } from './filter-entry';


export interface InsightsFilter { 
    context?: Context;
    filters?: Array<FilterEntry>;
}

