/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Column } from './column';
import { FilterEntry } from './filter-entry';
import { Sort } from './sort';
import { Chart } from './chart';


export interface InsightsViewResponse { 
    id?: string;
    insightType?: string;
    name?: string;
    description?: string;
    shared?: boolean;
    readOnly?: boolean;
    callouts?: Array<string>;
    charts?: Array<Chart>;
    columns?: Array<Column>;
    filters?: Array<FilterEntry>;
    sorts?: Array<Sort>;
    settings?: { [key: string]: object; };
}

