/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JobDetail { 
    id?: number;
    uri?: string;
    locale?: string;
    filename?: string;
    ditaType?: string;
    status?: JobDetail.StatusEnum;
}
export namespace JobDetail {
    export const StatusEnum = {
        Active: 'ACTIVE',
        Completed: 'COMPLETED',
        Cancelled: 'CANCELLED',
        Overdue: 'OVERDUE'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


