/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TopicmetaDto } from './topicmeta-dto';
import { TopicElementContentDto } from './topic-element-content-dto';


export interface KeyDefinitionDto { 
    keys?: Array<string>;
    sourceResourceUuid?: string;
    targetResourceUuid?: string;
    topicmeta?: TopicmetaDto;
    topicContent?: Array<TopicElementContentDto>;
    scopeHierarchy?: Array<Array<string>>;
    allQualifiedKeyNames?: Array<string>;
}

