/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LinkCounts { 
    incomingLinksCount?: number;
    outgoingLinksCount?: number;
    externalLinksCount?: number;
    brokenLinksCount?: number;
    explicitDependenciesCount?: number;
    explicitDependenciesExcludingResourceOnlyCount?: number;
}

