/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMetadata } from './page-metadata';
import { DependencyIssue } from './dependency-issue';


export interface PagedModelDependencyIssue { 
    content?: Array<DependencyIssue>;
    page?: PageMetadata;
}

