/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMetadata } from './page-metadata';
import { QualityScanProgressDto } from './quality-scan-progress-dto';


export interface PagedModelQualityScanProgressDto { 
    content?: Array<QualityScanProgressDto>;
    page?: PageMetadata;
}

