/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMetadata } from './page-metadata';
import { CommitOperationDetailDto } from './commit-operation-detail-dto';


export interface PagedModelCommitOperationDetailDto { 
    content?: Array<CommitOperationDetailDto>;
    page?: PageMetadata;
}

