/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMetadata } from './page-metadata';
import { CommitWithOpDto } from './commit-with-op-dto';


export interface PagedModelCommitWithOpDto { 
    content?: Array<CommitWithOpDto>;
    page?: PageMetadata;
}

