/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMetadata } from './page-metadata';
import { QualityIssueDto } from './quality-issue-dto';


export interface PagedModelQualityIssueDto { 
    content?: Array<QualityIssueDto>;
    page?: PageMetadata;
}

