/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMetadata } from './page-metadata';
import { ReleaseResponseDto } from './release-response-dto';


export interface PagedModelReleaseResponseDto { 
    content?: Array<ReleaseResponseDto>;
    page?: PageMetadata;
}

