/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QualityIssueLocationDto } from './quality-issue-location-dto';
import { QualityIssueQualityCheckDto } from './quality-issue-quality-check-dto';
import { QualityIssueResourceInfoDto } from './quality-issue-resource-info-dto';


export interface QualityIssueDto { 
    qualityCheck?: QualityIssueQualityCheckDto;
    issueUuid?: string;
    message?: string;
    severityCode?: string;
    issueType?: string;
    createdUtc?: string;
    resourceInfo?: QualityIssueResourceInfoDto;
    location?: QualityIssueLocationDto;
}

