/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PagedQualityIssues } from './paged-quality-issues';


export interface QualityIssuesPageDto { 
    issues?: PagedQualityIssues;
    issuesByCategory?: { [key: string]: number; };
    issuesBySeverity?: { [key: string]: number; };
}

