/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface QualityScanProgressDto { 
    scanUuid?: string;
    resourceId?: string;
    revisionTimestamp?: string;
    qualityScanStatus?: QualityScanProgressDto.QualityScanStatusEnum;
    startedUtc?: string;
    completedUtc?: string;
    durationMilliseconds?: number;
    totalIssuesFound?: number;
    totalResourcesScanned?: number;
    totalResourcesWithIssues?: number;
    totalResourcesIncluded?: number;
    totalResourcesExcluded?: number;
    issueSummary?: { [key: string]: number; };
}
export namespace QualityScanProgressDto {
    export const QualityScanStatusEnum = {
        Running: 'RUNNING',
        Completed: 'COMPLETED',
        Failed: 'FAILED',
        Created: 'CREATED'
    } as const;
    export type QualityScanStatusEnum = typeof QualityScanStatusEnum[keyof typeof QualityScanStatusEnum];
}


