/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface QualityIssueQualityCheckDto { 
    qualityCheckCode?: string;
    qualityCheckName?: string;
    qualityCheckDescription?: string;
    severity?: QualityIssueQualityCheckDto.SeverityEnum;
    category?: QualityIssueQualityCheckDto.CategoryEnum;
}
export namespace QualityIssueQualityCheckDto {
    export const SeverityEnum = {
        Info: 'INFO',
        Warning: 'WARNING',
        Error: 'ERROR',
        Critical: 'CRITICAL'
    } as const;
    export type SeverityEnum = typeof SeverityEnum[keyof typeof SeverityEnum];
    export const CategoryEnum = {
        Linking: 'LINKING',
        ValidationAndStructure: 'VALIDATION_AND_STRUCTURE',
        Accessibility: 'ACCESSIBILITY',
        LocalizationReadiness: 'LOCALIZATION_READINESS',
        AiReadiness: 'AI_READINESS',
        Unknown: 'UNKNOWN',
        MetadataAndSeo: 'METADATA_AND_SEO',
        GovernanceAndLifecycle: 'GOVERNANCE_AND_LIFECYCLE'
    } as const;
    export type CategoryEnum = typeof CategoryEnum[keyof typeof CategoryEnum];
}


