/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReleaseDetails { 
    deprecated?: boolean;
    releaseName?: string;
    branchId?: number;
    releaseResourceId?: number;
    legacyReleaseXml?: string;
    deprecatedUtc?: string;
    branchOfOriginName?: string;
}

