/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Branch } from './branch';
import { ResourceVersionResponseDto } from './resource-version-response-dto';


export interface ReleaseResponseDto { 
    branch?: Branch;
    pathToReleasedResources?: string;
    releasedResource?: ResourceVersionResponseDto;
}

