/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResourceVersionResponseDto { 
    resourceUuid?: string;
    ditaType?: ResourceVersionResponseDto.DitaTypeEnum;
    branchName?: string;
    resourceCreateTime?: string;
    path?: string;
    ezdPath?: string;
    fileName?: string;
    uuid?: string;
    directoryUuid?: string;
    ownerUsername?: string;
    creatorUsername?: string;
    lastModified?: string;
    contentMimeType?: string;
    metadata?: { [key: string]: string; };
    permOwner?: string;
    ownerGroup?: string;
    mode?: string;
    contentHashMd5?: string;
    contentHashSha256?: string;
}
export namespace ResourceVersionResponseDto {
    export const DitaTypeEnum = {
        NonDita: 'NON_DITA',
        Map: 'MAP',
        Topic: 'TOPIC'
    } as const;
    export type DitaTypeEnum = typeof DitaTypeEnum[keyof typeof DitaTypeEnum];
}


