/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResourceVersionLink { 
    attributeName?: string;
    elementName?: string;
    scope?: ResourceVersionLink.ScopeEnum;
    linkType?: ResourceVersionLink.LinkTypeEnum;
    brokenLink?: boolean;
    externalLink?: boolean;
    validLink?: boolean;
    externalLinkPath?: string;
    sourceResourceUuid?: string;
    destinationPath?: string;
    elementNumber?: number;
    destinationTopicId?: string;
    processingRoleResourceOnly?: boolean;
    destinationElementId?: string;
    destinationResourceUuid?: string;
    destinationExternalLink?: string;
}
export namespace ResourceVersionLink {
    export const ScopeEnum = {
        Local: 'LOCAL',
        Peer: 'PEER',
        External: 'EXTERNAL'
    } as const;
    export type ScopeEnum = typeof ScopeEnum[keyof typeof ScopeEnum];
    export const LinkTypeEnum = {
        Valid: 'VALID',
        Broken: 'BROKEN',
        External: 'EXTERNAL'
    } as const;
    export type LinkTypeEnum = typeof LinkTypeEnum[keyof typeof LinkTypeEnum];
}


