/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ScanSummaryDto { 
    scanUuid?: string;
    scanId?: number;
    qualityScanStatus?: ScanSummaryDto.QualityScanStatusEnum;
    scanTimestamp?: string;
    issuesByCategory?: { [key: string]: number; };
    issuesBySeverity?: { [key: string]: number; };
    totalFiles?: number;
    filesIncluded?: number;
    filesExcluded?: number;
    totalIssues?: number;
    topicsWithCritical?: number;
    topicsWithError?: number;
    topicsWithWarning?: number;
    topicsWithInfo?: number;
    topicsClean?: number;
}
export namespace ScanSummaryDto {
    export const QualityScanStatusEnum = {
        Running: 'RUNNING',
        Completed: 'COMPLETED',
        Failed: 'FAILED',
        Created: 'CREATED'
    } as const;
    export type QualityScanStatusEnum = typeof QualityScanStatusEnum[keyof typeof QualityScanStatusEnum];
}


