/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ScheduleIntervalDto { 
    value?: number;
    unit: ScheduleIntervalDto.UnitEnum;
}
export namespace ScheduleIntervalDto {
    export const UnitEnum = {
        Minute: 'MINUTE',
        Hour: 'HOUR',
        Day: 'DAY',
        Week: 'WEEK'
    } as const;
    export type UnitEnum = typeof UnitEnum[keyof typeof UnitEnum];
}


