/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Context } from './context';
import { ScheduleIntervalDto } from './schedule-interval-dto';
import { ContextInfo } from './context-info';


export interface SnapshotScheduleDto { 
    scheduleId?: number;
    interval?: ScheduleIntervalDto;
    context?: Context;
    contextInfo?: ContextInfo;
    enabled?: boolean;
    lastRunAt?: string;
    snapshotCount?: number;
}

