/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SortField { 
    field?: string;
    direction: SortField.DirectionEnum;
}
export namespace SortField {
    export const DirectionEnum = {
        Asc: 'asc',
        Desc: 'desc'
    } as const;
    export type DirectionEnum = typeof DirectionEnum[keyof typeof DirectionEnum];
}


