/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SyncResourceInfo { 
    uri?: string;
    mimeType?: string;
    createdDate?: string;
    lastModifiedDate?: string;
    metadata?: { [key: string]: string; };
    permissionXml?: string;
}

