/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TrendsConfig { 
    start?: string;
    end?: string;
    bucket: TrendsConfig.BucketEnum;
}
export namespace TrendsConfig {
    export const BucketEnum = {
        Minute: 'MINUTE',
        Hour: 'HOUR',
        Day: 'DAY',
        Week: 'WEEK',
        Month: 'MONTH',
        Quarter: 'QUARTER',
        Year: 'YEAR'
    } as const;
    export type BucketEnum = typeof BucketEnum[keyof typeof BucketEnum];
}


