/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScheduleIntervalDto } from './schedule-interval-dto';


export interface UpdateScheduleRequest { 
    enabled?: boolean;
    interval?: ScheduleIntervalDto;
}

