/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateDefinitionRequest { 
    name?: string;
    key?: string;
    dataType: UpdateDefinitionRequest.DataTypeEnum;
    defaultValue?: string;
    multiValue?: boolean;
    ordinal?: number;
    xpaths?: Array<string>;
}
export namespace UpdateDefinitionRequest {
    export const DataTypeEnum = {
        Text: 'TEXT',
        Date: 'DATE',
        Uuid: 'UUID',
        Boolean: 'BOOLEAN',
        Decimal: 'DECIMAL'
    } as const;
    export type DataTypeEnum = typeof DataTypeEnum[keyof typeof DataTypeEnum];
}


