/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VersionInfoDto { 
    tags?: string;
    commitId?: string;
    branch?: string;
    buildTime?: string;
    commitTime?: string;
}

